version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dev:
    image: cosmtrek/air
    container_name: go_air_dev
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: air

volumes:
  postgres_data:
