FROM golang:1.25-alpine

RUN apk add --no-cache git curl build-base
RUN apk add --no-cache git curl build-base postgresql-client
RUN go install github.com/air-verse/air@latest \
 && go install github.com/pressly/goose/v3/cmd/goose@latest \
 && go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

WORKDIR /app
CMD ["air"]