// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExerciseSession = `-- name: CreateExerciseSession :one
INSERT INTO user_exercise_sessions (
  user_id, exercise_type_id, start_time_utc, end_time_utc
) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, exercise_type_id, start_time_utc, end_time_utc
`

type CreateExerciseSessionParams struct {
	UserID         string             `json:"user_id"`
	ExerciseTypeID string             `json:"exercise_type_id"`
	StartTimeUtc   pgtype.Timestamptz `json:"start_time_utc"`
	EndTimeUtc     pgtype.Timestamptz `json:"end_time_utc"`
}

func (q *Queries) CreateExerciseSession(ctx context.Context, arg CreateExerciseSessionParams) (UserExerciseSession, error) {
	row := q.db.QueryRow(ctx, createExerciseSession,
		arg.UserID,
		arg.ExerciseTypeID,
		arg.StartTimeUtc,
		arg.EndTimeUtc,
	)
	var i UserExerciseSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseTypeID,
		&i.StartTimeUtc,
		&i.EndTimeUtc,
	)
	return i, err
}

const finishExerciseSession = `-- name: FinishExerciseSession :one
UPDATE user_exercise_sessions
SET end_time_utc = $2
WHERE id = $1
RETURNING id, user_id, exercise_type_id, start_time_utc, end_time_utc
`

type FinishExerciseSessionParams struct {
	ID         string             `json:"id"`
	EndTimeUtc pgtype.Timestamptz `json:"end_time_utc"`
}

func (q *Queries) FinishExerciseSession(ctx context.Context, arg FinishExerciseSessionParams) (UserExerciseSession, error) {
	row := q.db.QueryRow(ctx, finishExerciseSession, arg.ID, arg.EndTimeUtc)
	var i UserExerciseSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseTypeID,
		&i.StartTimeUtc,
		&i.EndTimeUtc,
	)
	return i, err
}

const getExerciseSession = `-- name: GetExerciseSession :one
SELECT id, user_id, exercise_type_id, start_time_utc, end_time_utc FROM user_exercise_sessions WHERE id = $1
`

func (q *Queries) GetExerciseSession(ctx context.Context, id string) (UserExerciseSession, error) {
	row := q.db.QueryRow(ctx, getExerciseSession, id)
	var i UserExerciseSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseTypeID,
		&i.StartTimeUtc,
		&i.EndTimeUtc,
	)
	return i, err
}

const listExerciseSessionsByUser = `-- name: ListExerciseSessionsByUser :many
SELECT id, user_id, exercise_type_id, start_time_utc, end_time_utc
FROM user_exercise_sessions
WHERE user_id = $1
ORDER BY start_time_utc DESC
LIMIT $2 OFFSET $3
`

type ListExerciseSessionsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListExerciseSessionsByUser(ctx context.Context, arg ListExerciseSessionsByUserParams) ([]UserExerciseSession, error) {
	rows, err := q.db.Query(ctx, listExerciseSessionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserExerciseSession
	for rows.Next() {
		var i UserExerciseSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseTypeID,
			&i.StartTimeUtc,
			&i.EndTimeUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
