// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_types.sql

package db

import (
	"context"
)

const listExerciseTypes = `-- name: ListExerciseTypes :many
SELECT id, name FROM exercise_types ORDER BY name
`

func (q *Queries) ListExerciseTypes(ctx context.Context) ([]ExerciseType, error) {
	rows, err := q.db.Query(ctx, listExerciseTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseType
	for rows.Next() {
		var i ExerciseType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExerciseTypeByName = `-- name: UpsertExerciseTypeByName :one
INSERT INTO exercise_types (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertExerciseTypeByName(ctx context.Context, name string) (ExerciseType, error) {
	row := q.db.QueryRow(ctx, upsertExerciseTypeByName, name)
	var i ExerciseType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
