// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_session_repetitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepetition = `-- name: CreateRepetition :one
INSERT INTO exercise_session_repetitions (
  exercise_session_id, rep_index,
  avg_range_of_motion, peak_range_of_motion,
  avg_angle_velocity,  peak_angle_velocity
) VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (exercise_session_id, rep_index) DO UPDATE
  SET avg_range_of_motion  = EXCLUDED.avg_range_of_motion,
      peak_range_of_motion = EXCLUDED.peak_range_of_motion,
      avg_angle_velocity   = EXCLUDED.avg_angle_velocity,
      peak_angle_velocity  = EXCLUDED.peak_angle_velocity
RETURNING id, exercise_session_id, rep_index, avg_range_of_motion, peak_range_of_motion, avg_angle_velocity, peak_angle_velocity
`

type CreateRepetitionParams struct {
	ExerciseSessionID string        `json:"exercise_session_id"`
	RepIndex          pgtype.Int4   `json:"rep_index"`
	AvgRangeOfMotion  pgtype.Float4 `json:"avg_range_of_motion"`
	PeakRangeOfMotion pgtype.Float4 `json:"peak_range_of_motion"`
	AvgAngleVelocity  pgtype.Float4 `json:"avg_angle_velocity"`
	PeakAngleVelocity pgtype.Float4 `json:"peak_angle_velocity"`
}

func (q *Queries) CreateRepetition(ctx context.Context, arg CreateRepetitionParams) (ExerciseSessionRepetition, error) {
	row := q.db.QueryRow(ctx, createRepetition,
		arg.ExerciseSessionID,
		arg.RepIndex,
		arg.AvgRangeOfMotion,
		arg.PeakRangeOfMotion,
		arg.AvgAngleVelocity,
		arg.PeakAngleVelocity,
	)
	var i ExerciseSessionRepetition
	err := row.Scan(
		&i.ID,
		&i.ExerciseSessionID,
		&i.RepIndex,
		&i.AvgRangeOfMotion,
		&i.PeakRangeOfMotion,
		&i.AvgAngleVelocity,
		&i.PeakAngleVelocity,
	)
	return i, err
}

const listRepetitionsForSession = `-- name: ListRepetitionsForSession :many
SELECT id, exercise_session_id, rep_index, avg_range_of_motion, peak_range_of_motion, avg_angle_velocity, peak_angle_velocity
FROM exercise_session_repetitions
WHERE exercise_session_id = $1
ORDER BY rep_index NULLS LAST
`

func (q *Queries) ListRepetitionsForSession(ctx context.Context, exerciseSessionID string) ([]ExerciseSessionRepetition, error) {
	rows, err := q.db.Query(ctx, listRepetitionsForSession, exerciseSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSessionRepetition
	for rows.Next() {
		var i ExerciseSessionRepetition
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseSessionID,
			&i.RepIndex,
			&i.AvgRangeOfMotion,
			&i.PeakRangeOfMotion,
			&i.AvgAngleVelocity,
			&i.PeakAngleVelocity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
