// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_session_joint_samples.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSamplesForSession = `-- name: DeleteSamplesForSession :exec
DELETE FROM exercise_session_joint_samples WHERE exercise_session_id = $1
`

func (q *Queries) DeleteSamplesForSession(ctx context.Context, exerciseSessionID string) error {
	_, err := q.db.Exec(ctx, deleteSamplesForSession, exerciseSessionID)
	return err
}

const getSamplesInRange = `-- name: GetSamplesInRange :many
SELECT id, exercise_session_id, pitch_angle, yaw_angle, roll_angle, timestamp_ms, ax_mps2, ay_mps2, az_mps2, gx_dps, gy_dps, gz_dps
FROM exercise_session_joint_samples
WHERE exercise_session_id = $1
  AND timestamp_ms BETWEEN $2 AND $3
ORDER BY timestamp_ms
`

type GetSamplesInRangeParams struct {
	ExerciseSessionID string      `json:"exercise_session_id"`
	TimestampMs       pgtype.Int4 `json:"timestamp_ms"`
	TimestampMs_2     pgtype.Int4 `json:"timestamp_ms_2"`
}

func (q *Queries) GetSamplesInRange(ctx context.Context, arg GetSamplesInRangeParams) ([]ExerciseSessionJointSample, error) {
	rows, err := q.db.Query(ctx, getSamplesInRange, arg.ExerciseSessionID, arg.TimestampMs, arg.TimestampMs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSessionJointSample
	for rows.Next() {
		var i ExerciseSessionJointSample
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseSessionID,
			&i.PitchAngle,
			&i.YawAngle,
			&i.RollAngle,
			&i.TimestampMs,
			&i.AxMps2,
			&i.AyMps2,
			&i.AzMps2,
			&i.GxDps,
			&i.GyDps,
			&i.GzDps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJointSample = `-- name: InsertJointSample :exec
INSERT INTO exercise_session_joint_samples (
  exercise_session_id, timestamp_ms,
  pitch_angle, yaw_angle, roll_angle,
  ax_mps2, ay_mps2, az_mps2,
  gx_dps, gy_dps, gz_dps
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11
)
`

type InsertJointSampleParams struct {
	ExerciseSessionID string        `json:"exercise_session_id"`
	TimestampMs       pgtype.Int4   `json:"timestamp_ms"`
	PitchAngle        pgtype.Float4 `json:"pitch_angle"`
	YawAngle          pgtype.Float4 `json:"yaw_angle"`
	RollAngle         pgtype.Float4 `json:"roll_angle"`
	AxMps2            pgtype.Float4 `json:"ax_mps2"`
	AyMps2            pgtype.Float4 `json:"ay_mps2"`
	AzMps2            pgtype.Float4 `json:"az_mps2"`
	GxDps             pgtype.Float4 `json:"gx_dps"`
	GyDps             pgtype.Float4 `json:"gy_dps"`
	GzDps             pgtype.Float4 `json:"gz_dps"`
}

func (q *Queries) InsertJointSample(ctx context.Context, arg InsertJointSampleParams) error {
	_, err := q.db.Exec(ctx, insertJointSample,
		arg.ExerciseSessionID,
		arg.TimestampMs,
		arg.PitchAngle,
		arg.YawAngle,
		arg.RollAngle,
		arg.AxMps2,
		arg.AyMps2,
		arg.AzMps2,
		arg.GxDps,
		arg.GyDps,
		arg.GzDps,
	)
	return err
}
