// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        string             `json:"id"`
	ClerkID   string             `json:"clerk_id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserCalibration struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	StandingYawAngle   float64            `json:"standing_yaw_angle"`
	StandingPitchAngle float64            `json:"standing_pitch_angle"`
	StandingRollAngle  float64            `json:"standing_roll_angle"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type WorkoutSession struct {
	ID                    string             `json:"id"`
	UserID                string             `json:"user_id"`
	WorkoutTypeID         string             `json:"workout_type_id"`
	CalibrationYawAngle   pgtype.Float8      `json:"calibration_yaw_angle"`
	CalibrationPitchAngle pgtype.Float8      `json:"calibration_pitch_angle"`
	CalibrationRollAngle  pgtype.Float8      `json:"calibration_roll_angle"`
	StartTime             pgtype.Timestamptz `json:"start_time"`
	EndTime               pgtype.Timestamptz `json:"end_time"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type WorkoutType struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Config      []byte             `json:"config"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
