// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_calibration.sql

package db

import (
	"context"
)

const deleteUserCalibrationByUserID = `-- name: DeleteUserCalibrationByUserID :exec
DELETE FROM user_calibration WHERE user_id = $1
`

func (q *Queries) DeleteUserCalibrationByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserCalibrationByUserID, userID)
	return err
}

const getUserCalibrationByUserID = `-- name: GetUserCalibrationByUserID :one
SELECT id, user_id, standing_yaw_angle, standing_pitch_angle, standing_roll_angle, created_at, updated_at FROM user_calibration WHERE user_id = $1
`

func (q *Queries) GetUserCalibrationByUserID(ctx context.Context, userID string) (UserCalibration, error) {
	row := q.db.QueryRow(ctx, getUserCalibrationByUserID, userID)
	var i UserCalibration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StandingYawAngle,
		&i.StandingPitchAngle,
		&i.StandingRollAngle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserCalibration = `-- name: UpsertUserCalibration :one
INSERT INTO user_calibration (
    user_id,
    standing_yaw_angle,
    standing_pitch_angle,
    standing_roll_angle,
    updated_at
)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    standing_yaw_angle = EXCLUDED.standing_yaw_angle,
    standing_pitch_angle = EXCLUDED.standing_pitch_angle,
    standing_roll_angle = EXCLUDED.standing_roll_angle,
    updated_at = NOW()
RETURNING id, user_id, standing_yaw_angle, standing_pitch_angle, standing_roll_angle, created_at, updated_at
`

type UpsertUserCalibrationParams struct {
	UserID             string  `json:"user_id"`
	StandingYawAngle   float64 `json:"standing_yaw_angle"`
	StandingPitchAngle float64 `json:"standing_pitch_angle"`
	StandingRollAngle  float64 `json:"standing_roll_angle"`
}

// If a calibration already exists for the user, update it with the new values and set updated_at to the current time
func (q *Queries) UpsertUserCalibration(ctx context.Context, arg UpsertUserCalibrationParams) (UserCalibration, error) {
	row := q.db.QueryRow(ctx, upsertUserCalibration,
		arg.UserID,
		arg.StandingYawAngle,
		arg.StandingPitchAngle,
		arg.StandingRollAngle,
	)
	var i UserCalibration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StandingYawAngle,
		&i.StandingPitchAngle,
		&i.StandingRollAngle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
