// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_calibration.sql

package db

import (
	"context"
)

const deleteUserCalibration = `-- name: DeleteUserCalibration :exec
DELETE FROM user_calibration WHERE user_id = $1
`

func (q *Queries) DeleteUserCalibration(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserCalibration, userID)
	return err
}

const getUserCalibrationByUserID = `-- name: GetUserCalibrationByUserID :one
SELECT id, user_id, standing_angle, standing_flex, created_at, updated_at FROM user_calibration WHERE user_id = $1
`

func (q *Queries) GetUserCalibrationByUserID(ctx context.Context, userID string) (UserCalibration, error) {
	row := q.db.QueryRow(ctx, getUserCalibrationByUserID, userID)
	var i UserCalibration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StandingAngle,
		&i.StandingFlex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserCalibration = `-- name: UpsertUserCalibration :one
INSERT INTO user_calibration (user_id, standing_angle, standing_flex, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id)
DO UPDATE SET
    standing_angle = EXCLUDED.standing_angle,
    standing_flex = EXCLUDED.standing_flex,
    updated_at = NOW()
RETURNING id, user_id, standing_angle, standing_flex, created_at, updated_at
`

type UpsertUserCalibrationParams struct {
	UserID        string  `json:"user_id"`
	StandingAngle float64 `json:"standing_angle"`
	StandingFlex  float64 `json:"standing_flex"`
}

func (q *Queries) UpsertUserCalibration(ctx context.Context, arg UpsertUserCalibrationParams) (UserCalibration, error) {
	row := q.db.QueryRow(ctx, upsertUserCalibration, arg.UserID, arg.StandingAngle, arg.StandingFlex)
	var i UserCalibration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StandingAngle,
		&i.StandingFlex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
