// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_set.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkoutSet = `-- name: CreateWorkoutSet :one
INSERT INTO workout_set (workout_session_id, set_number, start_time, end_time, coaching_score)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workout_session_id, set_number, start_time, end_time, coaching_score, created_at, updated_at
`

type CreateWorkoutSetParams struct {
	WorkoutSessionID string             `json:"workout_session_id"`
	SetNumber        int32              `json:"set_number"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	CoachingScore    []byte             `json:"coaching_score"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRow(ctx, createWorkoutSet,
		arg.WorkoutSessionID,
		arg.SetNumber,
		arg.StartTime,
		arg.EndTime,
		arg.CoachingScore,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.SetNumber,
		&i.StartTime,
		&i.EndTime,
		&i.CoachingScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetsByWorkoutSessionId = `-- name: GetSetsByWorkoutSessionId :many
SELECT id, workout_session_id, set_number, start_time, end_time, coaching_score, created_at, updated_at FROM workout_set WHERE workout_session_id = $1 ORDER BY set_number ASC
`

func (q *Queries) GetSetsByWorkoutSessionId(ctx context.Context, workoutSessionID string) ([]WorkoutSet, error) {
	rows, err := q.db.Query(ctx, getSetsByWorkoutSessionId, workoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSet
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutSessionID,
			&i.SetNumber,
			&i.StartTime,
			&i.EndTime,
			&i.CoachingScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
