// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkoutSession = `-- name: CreateWorkoutSession :one
INSERT INTO workout_session (user_id, workout_type_id, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, workout_type_id, start_time, end_time, created_at, updated_at
`

type CreateWorkoutSessionParams struct {
	UserID        string             `json:"user_id"`
	WorkoutTypeID string             `json:"workout_type_id"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, createWorkoutSession,
		arg.UserID,
		arg.WorkoutTypeID,
		arg.StartTime,
		arg.EndTime,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutTypeID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endWorkoutSession = `-- name: EndWorkoutSession :exec
UPDATE workout_session
SET end_time = $2, updated_at = NOW()
WHERE id = $1
`

type EndWorkoutSessionParams struct {
	ID      string             `json:"id"`
	EndTime pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) EndWorkoutSession(ctx context.Context, arg EndWorkoutSessionParams) error {
	_, err := q.db.Exec(ctx, endWorkoutSession, arg.ID, arg.EndTime)
	return err
}

const getUserWorkoutSessionHistory = `-- name: GetUserWorkoutSessionHistory :many
SELECT
    ws.id,
    ws.start_time,
    ws.end_time,
    wt.name as workout_type_name
FROM workout_session ws
JOIN workout_type wt ON ws.workout_type_id = wt.id
WHERE ws.user_id = $1
ORDER BY ws.start_time DESC
LIMIT $2
`

type GetUserWorkoutSessionHistoryParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type GetUserWorkoutSessionHistoryRow struct {
	ID              string             `json:"id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	WorkoutTypeName string             `json:"workout_type_name"`
}

func (q *Queries) GetUserWorkoutSessionHistory(ctx context.Context, arg GetUserWorkoutSessionHistoryParams) ([]GetUserWorkoutSessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserWorkoutSessionHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWorkoutSessionHistoryRow
	for rows.Next() {
		var i GetUserWorkoutSessionHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.WorkoutTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutSessionByID = `-- name: GetWorkoutSessionByID :one
SELECT id, user_id, workout_type_id, start_time, end_time, created_at, updated_at FROM workout_session WHERE id = $1
`

func (q *Queries) GetWorkoutSessionByID(ctx context.Context, id string) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getWorkoutSessionByID, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutTypeID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkoutSession = `-- name: UpdateWorkoutSession :one
UPDATE workout_session
SET workout_type_id = COALESCE($1, workout_type_id),
    start_time = COALESCE($2, start_time),
    end_time = COALESCE($3, end_time),
    updated_at = NOW()
WHERE id = $4
RETURNING id, user_id, workout_type_id, start_time, end_time, created_at, updated_at
`

type UpdateWorkoutSessionParams struct {
	WorkoutTypeID pgtype.Text        `json:"workout_type_id"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	ID            string             `json:"id"`
}

func (q *Queries) UpdateWorkoutSession(ctx context.Context, arg UpdateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, updateWorkoutSession,
		arg.WorkoutTypeID,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutTypeID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
