// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_session_set.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkoutSessionSet = `-- name: CreateWorkoutSessionSet :one
INSERT INTO workout_session_set (
    workout_session_id,
    set_number,
    start_time,
    end_time
)
VALUES ($1, $2, $3, $4)
RETURNING id, workout_session_id, set_number, start_time, end_time
`

type CreateWorkoutSessionSetParams struct {
	WorkoutSessionID string             `json:"workout_session_id"`
	SetNumber        int32              `json:"set_number"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CreateWorkoutSessionSet(ctx context.Context, arg CreateWorkoutSessionSetParams) (WorkoutSessionSet, error) {
	row := q.db.QueryRow(ctx, createWorkoutSessionSet,
		arg.WorkoutSessionID,
		arg.SetNumber,
		arg.StartTime,
		arg.EndTime,
	)
	var i WorkoutSessionSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionID,
		&i.SetNumber,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const getWorkoutSessionSetsBySessionID = `-- name: GetWorkoutSessionSetsBySessionID :many
SELECT id, workout_session_id, set_number, start_time, end_time
FROM workout_session_set
WHERE workout_session_id = $1
ORDER BY set_number ASC
`

func (q *Queries) GetWorkoutSessionSetsBySessionID(ctx context.Context, workoutSessionID string) ([]WorkoutSessionSet, error) {
	rows, err := q.db.Query(ctx, getWorkoutSessionSetsBySessionID, workoutSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSessionSet
	for rows.Next() {
		var i WorkoutSessionSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutSessionID,
			&i.SetNumber,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
