// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_session_set_rep.sql

package db

import (
	"context"
)

const createWorkoutSessionSetRep = `-- name: CreateWorkoutSessionSetRep :one
INSERT INTO workout_session_set_rep (
    workout_session_set_id,
    rep_number,
    start_time,
    end_time,
    samples,
    metrics
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workout_session_set_id, rep_number, start_time, end_time, samples, metrics, created_at, updated_at
`

type CreateWorkoutSessionSetRepParams struct {
	WorkoutSessionSetID string `json:"workout_session_set_id"`
	RepNumber           int32  `json:"rep_number"`
	StartTime           int64  `json:"start_time"`
	EndTime             int64  `json:"end_time"`
	Samples             []byte `json:"samples"`
	Metrics             []byte `json:"metrics"`
}

func (q *Queries) CreateWorkoutSessionSetRep(ctx context.Context, arg CreateWorkoutSessionSetRepParams) (WorkoutSessionSetRep, error) {
	row := q.db.QueryRow(ctx, createWorkoutSessionSetRep,
		arg.WorkoutSessionSetID,
		arg.RepNumber,
		arg.StartTime,
		arg.EndTime,
		arg.Samples,
		arg.Metrics,
	)
	var i WorkoutSessionSetRep
	err := row.Scan(
		&i.ID,
		&i.WorkoutSessionSetID,
		&i.RepNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Samples,
		&i.Metrics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutSessionSetRepsBySessionSetID = `-- name: GetWorkoutSessionSetRepsBySessionSetID :many
SELECT id, workout_session_set_id, rep_number, start_time, end_time, samples, metrics, created_at, updated_at
FROM workout_session_set_rep
WHERE workout_session_set_id = $1
ORDER BY rep_number ASC
`

func (q *Queries) GetWorkoutSessionSetRepsBySessionSetID(ctx context.Context, workoutSessionSetID string) ([]WorkoutSessionSetRep, error) {
	rows, err := q.db.Query(ctx, getWorkoutSessionSetRepsBySessionSetID, workoutSessionSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutSessionSetRep
	for rows.Next() {
		var i WorkoutSessionSetRep
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutSessionSetID,
			&i.RepNumber,
			&i.StartTime,
			&i.EndTime,
			&i.Samples,
			&i.Metrics,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
