// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_rep.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkoutRep = `-- name: CreateWorkoutRep :exec
INSERT INTO workout_rep (workout_set_id, rep_number, start_time, end_time, quality, peak_angle, avg_flex, sensor_data_points)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateWorkoutRepParams struct {
	WorkoutSetID     string             `json:"workout_set_id"`
	RepNumber        int32              `json:"rep_number"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	Quality          pgtype.Text        `json:"quality"`
	PeakAngle        pgtype.Float8      `json:"peak_angle"`
	AvgFlex          pgtype.Float8      `json:"avg_flex"`
	SensorDataPoints []byte             `json:"sensor_data_points"`
}

func (q *Queries) CreateWorkoutRep(ctx context.Context, arg CreateWorkoutRepParams) error {
	_, err := q.db.Exec(ctx, createWorkoutRep,
		arg.WorkoutSetID,
		arg.RepNumber,
		arg.StartTime,
		arg.EndTime,
		arg.Quality,
		arg.PeakAngle,
		arg.AvgFlex,
		arg.SensorDataPoints,
	)
	return err
}

const getRepsByWorkoutSetId = `-- name: GetRepsByWorkoutSetId :many
SELECT id, workout_set_id, rep_number, start_time, end_time, quality, peak_angle, avg_flex, sensor_data_points, created_at, updated_at FROM workout_rep WHERE workout_set_id = $1 ORDER BY rep_number ASC
`

func (q *Queries) GetRepsByWorkoutSetId(ctx context.Context, workoutSetID string) ([]WorkoutRep, error) {
	rows, err := q.db.Query(ctx, getRepsByWorkoutSetId, workoutSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutRep
	for rows.Next() {
		var i WorkoutRep
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutSetID,
			&i.RepNumber,
			&i.StartTime,
			&i.EndTime,
			&i.Quality,
			&i.PeakAngle,
			&i.AvgFlex,
			&i.SensorDataPoints,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
