// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkoutSession = `-- name: CreateWorkoutSession :one
INSERT INTO workout_session (
    user_id,
    workout_type_id,
    calibration_yaw_angle,
    calibration_pitch_angle,
    calibration_roll_angle,
    start_time,
    end_time)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, workout_type_id, calibration_yaw_angle, calibration_pitch_angle, calibration_roll_angle, start_time, end_time, created_at, updated_at
`

type CreateWorkoutSessionParams struct {
	UserID                string             `json:"user_id"`
	WorkoutTypeID         string             `json:"workout_type_id"`
	CalibrationYawAngle   pgtype.Float8      `json:"calibration_yaw_angle"`
	CalibrationPitchAngle pgtype.Float8      `json:"calibration_pitch_angle"`
	CalibrationRollAngle  pgtype.Float8      `json:"calibration_roll_angle"`
	StartTime             pgtype.Timestamptz `json:"start_time"`
	EndTime               pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CreateWorkoutSession(ctx context.Context, arg CreateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, createWorkoutSession,
		arg.UserID,
		arg.WorkoutTypeID,
		arg.CalibrationYawAngle,
		arg.CalibrationPitchAngle,
		arg.CalibrationRollAngle,
		arg.StartTime,
		arg.EndTime,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutTypeID,
		&i.CalibrationYawAngle,
		&i.CalibrationPitchAngle,
		&i.CalibrationRollAngle,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWorkoutSessionHistory = `-- name: GetUserWorkoutSessionHistory :many
SELECT
    ws.id,
    ws.user_id,
    ws.workout_type_id,
    ws.start_time,
    ws.end_time,
    wt.name as workout_type_name,
    COUNT(DISTINCT s.id)::int AS total_sets,
    COUNT(r.id)::int AS total_reps
FROM workout_session ws
JOIN workout_type wt 
    ON ws.workout_type_id = wt.id
LEFT JOIN workout_session_set s
    ON ws.id = s.workout_session_id
LEFT JOIN workout_session_set_rep r
    ON s.id = r.workout_session_set_id
WHERE ws.user_id = $1
GROUP BY
    ws.id,
    ws.user_id,
    ws.workout_type_id,
    wt.name,
    ws.start_time,
    ws.end_time
ORDER BY ws.start_time DESC
LIMIT $2
`

type GetUserWorkoutSessionHistoryParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type GetUserWorkoutSessionHistoryRow struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	WorkoutTypeID   string             `json:"workout_type_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	WorkoutTypeName string             `json:"workout_type_name"`
	TotalSets       int32              `json:"total_sets"`
	TotalReps       int32              `json:"total_reps"`
}

func (q *Queries) GetUserWorkoutSessionHistory(ctx context.Context, arg GetUserWorkoutSessionHistoryParams) ([]GetUserWorkoutSessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserWorkoutSessionHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWorkoutSessionHistoryRow
	for rows.Next() {
		var i GetUserWorkoutSessionHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutTypeID,
			&i.StartTime,
			&i.EndTime,
			&i.WorkoutTypeName,
			&i.TotalSets,
			&i.TotalReps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutSessionByID = `-- name: GetWorkoutSessionByID :one
SELECT id, user_id, workout_type_id, calibration_yaw_angle, calibration_pitch_angle, calibration_roll_angle, start_time, end_time, created_at, updated_at FROM workout_session WHERE id = $1
`

func (q *Queries) GetWorkoutSessionByID(ctx context.Context, id string) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, getWorkoutSessionByID, id)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutTypeID,
		&i.CalibrationYawAngle,
		&i.CalibrationPitchAngle,
		&i.CalibrationRollAngle,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkoutSession = `-- name: UpdateWorkoutSession :one
UPDATE workout_session
SET workout_type_id = COALESCE($1, workout_type_id),
    start_time = COALESCE($2, start_time),
    end_time = COALESCE($3, end_time),
    updated_at = NOW()
WHERE id = $4
RETURNING id, user_id, workout_type_id, calibration_yaw_angle, calibration_pitch_angle, calibration_roll_angle, start_time, end_time, created_at, updated_at
`

type UpdateWorkoutSessionParams struct {
	WorkoutTypeID pgtype.Text        `json:"workout_type_id"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	EndTime       pgtype.Timestamptz `json:"end_time"`
	ID            string             `json:"id"`
}

func (q *Queries) UpdateWorkoutSession(ctx context.Context, arg UpdateWorkoutSessionParams) (WorkoutSession, error) {
	row := q.db.QueryRow(ctx, updateWorkoutSession,
		arg.WorkoutTypeID,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
	)
	var i WorkoutSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutTypeID,
		&i.CalibrationYawAngle,
		&i.CalibrationPitchAngle,
		&i.CalibrationRollAngle,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
