// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_type.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkoutType = `-- name: CreateWorkoutType :one
INSERT INTO workout_type(name, description, config, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, config, image_url, created_at, updated_at
`

type CreateWorkoutTypeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	ImageUrl    pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateWorkoutType(ctx context.Context, arg CreateWorkoutTypeParams) (WorkoutType, error) {
	row := q.db.QueryRow(ctx, createWorkoutType,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ImageUrl,
	)
	var i WorkoutType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutType = `-- name: GetWorkoutType :one
SELECT id, name, description, config, image_url, created_at, updated_at FROM workout_type WHERE id = $1
`

func (q *Queries) GetWorkoutType(ctx context.Context, id string) (WorkoutType, error) {
	row := q.db.QueryRow(ctx, getWorkoutType, id)
	var i WorkoutType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutTypeList = `-- name: GetWorkoutTypeList :many
SELECT id, name, description, config, image_url, created_at, updated_at FROM workout_type ORDER BY name ASC
`

func (q *Queries) GetWorkoutTypeList(ctx context.Context) ([]WorkoutType, error) {
	rows, err := q.db.Query(ctx, getWorkoutTypeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutType
	for rows.Next() {
		var i WorkoutType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
