name: Reset Database

on:
  workflow_dispatch:
    inputs:
      confirm_reset:
        description: 'Type RESET to confirm'
        required: true
        type: string

jobs:
  reset-database:
    if: ${{ inputs.confirm_reset == 'RESET' && github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Run database reset
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          bash ./scripts/ci/reset_database.sh